"""Memory injector for GateClaw agent personality.

Writes Genesis memory blocks dynamically to GateClaw's agents folder
before session load, enabling GateClaw to "remember" past conversations.

Usage:
    python memory_injector.py telegram   # Telegram/TTS variant
    python memory_injector.py standard   # TUI/WebUI variant
    python memory_injector.py clear      # Remove memory block
"""

import sys
import os
from pathlib import Path
from datetime import datetime

# Genesis source folder
GENESIS_SRC = Path(__file__).parent / "src"
sys.path.insert(0, str(GENESIS_SRC))

# GateClaw agents folder (always in Roaming)
AGENTS_FOLDER = Path(r"C:\Users\uscha\AppData\Roaming\gateclaw\agent")
MEMORY_FILE = AGENTS_FOLDER / "gateclaw-memory.md"

# Auto-detect active database paths
LOCAL_APP_DATA = os.environ.get("LOCALAPPDATA", r"C:\Users\uscha\AppData\Local")
GATECLAW_DATA_DIR = os.path.join(LOCAL_APP_DATA, "gateclaw")

# Memory.db is in Roaming (where genesis writes facts)
# But check Local first as fallback
LOCAL_MEM_DB = os.path.join(GATECLAW_DATA_DIR, "memory.db")
ROAMING_MEM_DB = r"C:\Users\uscha\AppData\Roaming\gateclaw\memory.db"
GENESIS_DB_PATH = Path(LOCAL_MEM_DB if os.path.exists(LOCAL_MEM_DB) else ROAMING_MEM_DB)
GENESIS_VECTORS_PATH = Path(r"C:\Users\uscha\AppData\Roaming\gateclaw\vectors")


def write_memory_block(variant: str = "standard") -> bool:
    """
    Write Genesis memory block to GateClaw agents folder.

    Args:
        variant: "standard" (full markdown) or "telegram" (≤3 spoken sentences)

    Returns:
        True if written successfully
    """
    try:
        # Import Genesis
        from core.genesis import Genesis

        # Initialize Genesis (reuses existing DB if present)
        genesis = Genesis(
            db_path=str(GENESIS_DB_PATH),
            vectors_path=str(GENESIS_VECTORS_PATH),
            buffer_size=10,
            embedding_model="qwen3-embedding:0.6b",
            llm_model="Claude-4.6-Opus-2B",
        )

        # Generate memory block
        memory_block = genesis.get_memory_block(variant=variant)

        # Add timestamp header (for standard variant)
        if variant == "standard":
            header = f"""<!-- Generated by GateClaw Genesis {datetime.now().isoformat()} -->
<!-- DO NOT EDIT MANUALLY - This file is auto-generated -->

"""
            memory_block = header + memory_block
        else:
            # Telegram: add small timestamp marker
            memory_block = f"<!-- Genesis {datetime.now().strftime('%Y-%m-%d %H:%M')} -->\n{memory_block}"

        # Write to agents folder
        AGENTS_FOLDER.mkdir(parents=True, exist_ok=True)
        with open(MEMORY_FILE, "w", encoding="utf-8") as f:
            f.write(memory_block)

        genesis.close()

        print(f"Memory block written ({variant}): {MEMORY_FILE}")
        return True

    except Exception as e:
        print(f"Failed to write memory block: {e}")
        return False


def clear_memory_block() -> bool:
    """
    Remove the memory block file.

    Returns:
        True if removed or didn't exist
    """
    try:
        if MEMORY_FILE.exists():
            MEMORY_FILE.unlink()
            print(f"Memory block cleared: {MEMORY_FILE}")
        return True
    except Exception as e:
        print(f"Failed to clear memory block: {e}")
        return False


if __name__ == "__main__":
    # CLI usage: python memory_injector.py [telegram|standard|clear]
    import sys

    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "clear":
            clear_memory_block()
        else:
            write_memory_block(variant=cmd)
    else:
        # Default: write both
        print("Writing standard memory block...")
        write_memory_block(variant="standard")
        print("Writing telegram memory block...")
        write_memory_block(variant="telegram")
